export const CART_ADD = 'CART_ADD_ITEM';
export const CART_DEL = 'CART_DEL_ITEM';
export const CART_CLEAR = 'CART_CLEAR_ITEMS';
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';
